/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PetOwner;

import UserInterface.PetOwner.PetHealth.RequestJPanel;
import UserInterface.PetOwner.PetHealth.ManageHealthHistoryJPanel;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.PetOwnerUserAccount;
import UserInterface.PetOwner.Adoption.ListPetAdoptionInfoJPanel;
import UserInterface.PetOwner.Adoption.ViewAdoptionRequestJPanel;
import UserInterface.PetOwner.Adoption.ViewIndividualAdoptionListJPanel;
import UserInterface.PetOwner.Adoption.ViewOrganizationAdoptionListJPanel;
import UserInterface.PetOwner.PetHealth.ChooseDoctorJPanel;
import UserInterface.PetOwner.PetHealth.DrawChartJPanel;
import UserInterface.PetOwner.PetHealth.ViewAppointmentJPanel;
import UserInterface.PetOwner.ReportHomeless.ReportHomelessJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shaoy
 */
public class PetOwnerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PetOwnerWorkAreaJPanel
     */
    private EcoSystem business;
    private JPanel userProcessContainer;
    private PetOwnerUserAccount account;
    private Enterprise enterprise;
    private Organization organization;
    
    public PetOwnerWorkAreaJPanel(JPanel userProcessContainer, EcoSystem business, Enterprise enterprise, Organization organization, PetOwnerUserAccount account) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.organization = organization;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMP = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnMHH = new javax.swing.JButton();
        btnRHR = new javax.swing.JButton();
        btnMA = new javax.swing.JButton();
        btnMA1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnIAL = new javax.swing.JButton();
        btnOAL = new javax.swing.JButton();
        btnVYR = new javax.swing.JButton();
        btnLP = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnRHA = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("Pet Owner Work Area");

        btnMP.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        btnMP.setText("Manage Pets");
        btnMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pet Health", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18))); // NOI18N

        btnMHH.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        btnMHH.setText("Manage Health History");
        btnMHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMHHActionPerformed(evt);
            }
        });

        btnRHR.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        btnRHR.setText("Manage Health Review");
        btnRHR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRHRActionPerformed(evt);
            }
        });

        btnMA.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        btnMA.setText("Make Appointment");
        btnMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAActionPerformed(evt);
            }
        });

        btnMA1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        btnMA1.setText("Manage Appointment");
        btnMA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMA1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButton1.setText("History Chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRHR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMHH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMHH)
                .addGap(18, 18, 18)
                .addComponent(btnRHR)
                .addGap(67, 67, 67)
                .addComponent(btnMA1)
                .addGap(18, 18, 18)
                .addComponent(btnMA)
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adoption Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18))); // NOI18N

        btnIAL.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        btnIAL.setText("Individual Adoption List");
        btnIAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIALActionPerformed(evt);
            }
        });

        btnOAL.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        btnOAL.setText("Organization Adoption List");
        btnOAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOALActionPerformed(evt);
            }
        });

        btnVYR.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        btnVYR.setText("View Your Request");
        btnVYR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVYRActionPerformed(evt);
            }
        });

        btnLP.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        btnLP.setText("List Pet");
        btnLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIAL, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(btnOAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVYR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIAL)
                .addGap(18, 18, 18)
                .addComponent(btnOAL)
                .addGap(66, 66, 66)
                .addComponent(btnVYR)
                .addGap(18, 18, 18)
                .addComponent(btnLP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report Homeless Animal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 18))); // NOI18N

        btnRHA.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        btnRHA.setText("Report Homeless Animal");
        btnRHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRHAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnRHA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMP, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(266, 266, 266))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(btnMP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPActionPerformed
        // TODO add your handling code here:
        ManagePetsJPanel managePetsJPanel = new ManagePetsJPanel(userProcessContainer, business, account);
        userProcessContainer.add("managePetsJPanel", managePetsJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnMPActionPerformed

    private void btnMHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMHHActionPerformed
        // TODO add your handling code here:
        ManageHealthHistoryJPanel manageHealthHistoryJPanel = new ManageHealthHistoryJPanel(userProcessContainer, business, account);
        userProcessContainer.add("managePetsJPanel", manageHealthHistoryJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMHHActionPerformed

    private void btnRHRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRHRActionPerformed
        // TODO add your handling code here:
        RequestJPanel requestJPanel = new RequestJPanel(userProcessContainer, business, enterprise, account);
        userProcessContainer.add("requestJPanel", requestJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRHRActionPerformed

    private void btnRHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRHAActionPerformed
        // TODO add your handling code here:
        ReportHomelessJPanel reportHomelessJPanel = new ReportHomelessJPanel(userProcessContainer, business, enterprise, account);
        userProcessContainer.add("reportHomelessJPanel", reportHomelessJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRHAActionPerformed

    private void btnOALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOALActionPerformed
        // TODO add your handling code here:
        ViewOrganizationAdoptionListJPanel viewOrganizationAdoptionListJPanel = new ViewOrganizationAdoptionListJPanel(userProcessContainer, business, enterprise, account);
        userProcessContainer.add("viewOrganizationAdoptionListJPanel", viewOrganizationAdoptionListJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOALActionPerformed

    private void btnVYRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVYRActionPerformed
        // TODO add your handling code here:
        ViewAdoptionRequestJPanel viewAdoptionRequestJPanel = new ViewAdoptionRequestJPanel(userProcessContainer, business, enterprise, account);
        userProcessContainer.add("viewAdoptionRequestJPanel", viewAdoptionRequestJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnVYRActionPerformed

    private void btnIALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIALActionPerformed
        // TODO add your handling code here:
        ViewIndividualAdoptionListJPanel viewIndividualAdoptionListJPanel = new ViewIndividualAdoptionListJPanel(userProcessContainer, business, organization, account);
        userProcessContainer.add("viewIndividualAdoptionListJPanel", viewIndividualAdoptionListJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnIALActionPerformed

    private void btnLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLPActionPerformed
        // TODO add your handling code here:
        ListPetAdoptionInfoJPanel listPetAdoptionInfoJPanel = new ListPetAdoptionInfoJPanel(userProcessContainer, account);
        userProcessContainer.add("listPetAdoptionInfoJPanel", listPetAdoptionInfoJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnLPActionPerformed

    private void btnMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAActionPerformed
        // TODO add your handling code here:
        ChooseDoctorJPanel makeappointmentJPanel = new ChooseDoctorJPanel(userProcessContainer,business, enterprise, account);
        userProcessContainer.add("makeappointmentJPanel", makeappointmentJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnMAActionPerformed

    private void btnMA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMA1ActionPerformed
        // TODO add your handling code here:
        ViewAppointmentJPanel viewappointmentJPanel = new ViewAppointmentJPanel(userProcessContainer,account);
        userProcessContainer.add("viewDiseaseJPanel",viewappointmentJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnMA1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DrawChartJPanel drawChartJPanel = new DrawChartJPanel(userProcessContainer,organization, account);
        userProcessContainer.add("drawChartJPanel", drawChartJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIAL;
    private javax.swing.JButton btnLP;
    private javax.swing.JButton btnMA;
    private javax.swing.JButton btnMA1;
    private javax.swing.JButton btnMHH;
    private javax.swing.JButton btnMP;
    private javax.swing.JButton btnOAL;
    private javax.swing.JButton btnRHA;
    private javax.swing.JButton btnRHR;
    private javax.swing.JButton btnVYR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
