/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Admin;

import Business.Enterprise.Enterprise;
import Business.Organization.HealthCareOrganization;
import javax.swing.JPanel;
import Business.Organization.Organization;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;

/**
 *
 * @author shaoy
 */
public class ViewReportChartJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewReportChartJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    
    public ViewReportChartJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        draw();
    }

    private void draw(){
        try {
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
                if(o instanceof HealthCareOrganization){
                    dataset.addValue(o.getWorkQueue().getTotalReport(),"",o.getName());
                }
            }
            
            JFreeChart chart = ChartFactory.createBarChart("Total Number of Report", "HealthCare Organization", "Number of Report", dataset, PlotOrientation.VERTICAL, true, true, false);
            CategoryPlot plot = (CategoryPlot) chart.getPlot();
            BarRenderer renderer = new BarRenderer();
            plot.setRenderer(renderer);
            renderer.setBaseItemLabelGenerator(new StandardCategoryItemLabelGenerator()); 
            renderer.setBaseItemLabelsVisible(true); 
            ChartPanel cpanel = new ChartPanel(chart);
            drawjPanel.removeAll();
            drawjPanel.setLayout(new BorderLayout());
            drawjPanel.add(cpanel, BorderLayout.CENTER);
            drawjPanel.validate();
            drawjPanel.repaint();
        } catch (Exception e) {
            throw e;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        drawjPanel = new javax.swing.JPanel();

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drawjPanelLayout = new javax.swing.GroupLayout(drawjPanel);
        drawjPanel.setLayout(drawjPanelLayout);
        drawjPanelLayout.setHorizontalGroup(
            drawjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawjPanelLayout.setVerticalGroup(
            drawjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drawjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 711, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(drawjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel drawjPanel;
    // End of variables declaration//GEN-END:variables
}
